CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 6
PRINT_FREQ: 10

DATASET:
  DATASET: ade20k
  ROOT: data/
  TEST_SET: 'list/ade20k/val.lst'
  TRAIN_SET: 'list/ade20k/train.lst'
  NUM_CLASSES: 150
MODEL:
  NAME: pidnet_large
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/imagenet/PIDNet_L_ImageNet.pth.tar"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 520
  - 520
  BASE_SIZE: 520
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 120
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.02
  WD: 0.0001
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 11
TEST:
  IMAGE_SIZE:
  - 520
  - 520
  BASE_SIZE: 520
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
